NOT and IN filter
mvysny/vok-dataloader pull request #1
Opened 2018-11-25 22:34 UTC by stapel

This would allow you to use the NOT- and IN-operators, in SqlWhereBuilder you could write: ``!(Person::name `in` listOf("Peter", "Paul"))``

2018-11-25 22:49 UTC, stapel commented
I am not so sure about the `Collection`-type in InFilter though.

2018-11-25 23:09 UTC, stapel commented
Also, `foo in ()` (empty list) does not seem to be valid SQL, but I don't know what to do there.

2018-11-30 13:45 UTC, mvysny commented
Hey, thanks for the PR, looks great! Would you please try to add one-two tests for this?

2018-11-30 14:06 UTC, mvysny requested changes
Looks great! I have added a couple of items to discuss, could you please look into those?

2018-12-10 11:09 UTC, mvysny reviewed
Awesome, thank you!

2018-12-10 11:09 UTC, mvysny commented on src/main/kotlin/com/github/mvysny/vokdataloader/Filters.kt
> +    infix fun <R> KProperty1<T, R>.`in`(value: R): Filter<T> = InFilter(name, value as Collection<Comparable<*>>)
Maybe the `in` function could only accept `Collection<R>` as a `value`?

2018-12-10 11:09 UTC, mvysny commented on src/main/kotlin/com/github/mvysny/vokdataloader/Filters.kt
> +data class InFilter<T: Any>(
Could you please add kdoc? Something along these lines:

> only matches items present in the [value] collection. For best in-memory performance we encourage you to only pass in [Set]. The in-memory matching is performed based on Collection.contains; other data providers may specify different criteria for comparison.

2018-12-10 11:09 UTC, mvysny commented on src/main/kotlin/com/github/mvysny/vokdataloader/Filters.kt
> +class NotFilter<T: Any>(val child: Filter<in T>) : Filter<T> {
Could you please add a very simple kdoc, e.g. "Matches anything that is not matched by the [child] filter. May not be supported by all data loaders, e.g. REST endpoints typically don't allow for this kind of filters"

2018-12-10 11:10 UTC, mvysny approved these changes

2018-12-10 11:10 UTC, merged

2018-12-10 19:19 UTC, stapel commented
Thanks, I had some troubles seeing your comments, I only got them via mail at first.
Also thanks for all your work!

2018-12-11 06:14 UTC, mvysny commented
Thank you for your contribution :+1:  I'm also new to this Github review system, it looked chatty and messy to me as well, I hope if I did that correctly :)